---
- name: remove service
  hosts: all
  become: true
  gather_facts: true

  roles:
    - init
  
  tasks:
    - name: stop service
      service:
        name: "{{ kibana_service_name }}"
        enabled: false
        state: stopped

    - name: remove systemd service file
      file:
        path: "/etc/systemd/system/{{ kibana_service_name }}.service"
        state: absent

    - name: remove install folder
      file:
        path: "{{ kibana_install_dir }}"
        state: absent
