- name: create certs dir
  file:
    path: "{{ kibana_install_dir }}/config/certs"
    state: directory
    owner: "{{ kibana_run_user }}"
    group: "{{ kibana_run_group }}"

- name: copy pem to certs dir
  copy:
    src: "certs/{{ item }}"
    dest: "{{ kibana_install_dir }}/config/certs/{{ item }}"
    owner: "{{ kibana_run_user }}"
    group: "{{ kibana_run_group }}"
  loop: 
    - ca.pem
    - wildcard.net.pem
    - wildcard.net-key.pem
  notify: restart kibana

- name: set kibana.yml config
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_install_dir }}/config/kibana.yml"
    owner: "{{ kibana_run_user }}"
    group: "{{ kibana_run_group }}"
  notify: restart kibana

- name: set kibana.service config
  template:
    src: kibana.service.j2
    dest: "/etc/systemd/system/{{ kibana_service_name }}.service"
    owner: "{{ kibana_run_user }}"
    group: "{{ kibana_run_group }}"
  notify: 
    - systemctl daemon-reload
    - restart kibana

- name: ensuring that handlers are executed
  meta: flush_handlers
